# Generated by Django 3.1.4 on 2021-05-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
