# Generated by Django 3.1.4 on 2021-05-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210526_2038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('title', 'image', 'title_url', 'summary', 'tag')},
        ),
    ]
